; Configuration file for BTT SKR 2 (firmware version 3)
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+10 on Wed Dec 15 2021 14:34:53 GMT+0100 (Mitteleuropäische Normalzeit)

; General preferences
G90                                            ; send absolute coordinates...
M83                                            ; ...but relative extruder moves
M550 P"Prusa Bear SKR 2.0 revo"                                ; set printer name

; Network
M552 S1                                        ; enable network
M586 P0 S1                                     ; enable HTTP
M586 P1 S0                                     ; disable FTP
M586 P2 S0                                     ; disable Telnet

; Drives
M569 P0 S0 D3 V40                                    ; physical drive 0 goes forwards using default driver timings
M569 P1 S0 D3 V40                                    ; physical drive 1 goes forwards using default driver timings
M569 P2 S0 D3 V0                                     ; physical drive 2 goes forwards using default driver timings
M569 P3 S0 D2                                        ; physical drive 3 goes forwards using default driver timings
M569 P4 S0 D3 V0                                     ; physical drive 3 goes forwards using default driver timings
M584 X0 Y1 Z2:4 E3							   ; two Z motors connected to driver outputs Z and E1 ; set drive mapping
M350 X16 Y16 Z16 E16 I1                        ; configure microstepping with interpolation
M92 X100.00 Y100.00 Z400.00 E420.00              ; set steps per mm
M566 X900.00 Y900.00 Z60.00 E120.00            ; set maximum instantaneous speed changes (mm/min)
M203 X6000.00 Y6000.00 Z300.00 E1200.00        ; set maximum speeds (mm/min)
M201 X750.00 Y750.00 Z25.00 E250.00            ; set accelerations (mm/s^2)
M906 X850 Y850 Z850 E900 I100                   ; set motor currents (mA) and motor idle factor in per cent
M84 S30                                        ; Set idle timeout

M671 X-20:220 Y0:0 S0.5 ; leadscrews at left (connected to Z) and right (connected to E1) of X axis

; Axis Limits
M208 X0 Y-4 Z0 S1                              ; set axis minima
M208 X250 Y210 Z200 S0                         ; set axis maxima
;M208 X-5:205 Y0:200 ; X carriage moves from -5 to 205, Y bed goes from 0 to 200

; Endstops
M574 X1 S3                                     ; configure sensorless endstop for low end on X
M574 Y1 S3                                     ; configure sensorless endstop for low end on Y
M574 Z1 S2                                     ; configure sensorless endstop for low end on Y

;M915 X Y S65 R0

; Stallgaurd Sensitivy
;M98 P"current-sense-normal.g"                              ; Current and Sensitivity for normal routine

; Z-Probe
M558 P2 C"probe" H5 F120 T6000                 ; set Z probe type to modulated and the dive height + speeds
G31 P500 X18 Y22 Z1.0                            ; set Z probe trigger value, offset and trigger height
M557 X15:215 Y11:195 S20                       ; define mesh grid

; Heaters
M308 S0 P"bedtemp" Y"thermistor" T100000 B4092 ; configure sensor 0 as thermistor on pin bedtemp
M950 H0 C"bed" T0                              ; create bed heater output on bed and map it to sensor 0
M307 H0 B0 S1.00                               ; disable bang-bang mode for the bed heater and set PWM limit
M140 H0                                        ; map heated bed to heater 0
M143 H0 S120                                   ; set temperature limit for heater 0 to 120C
M143 H0 S120                                   ; set temperature limit for heater 0 to 120C
M308 S1 P"e0temp" Y"thermistor" T100000 B4092  ; configure sensor 1 as thermistor on pin e0temp
M950 H1 C"e0heat" T1                           ; create nozzle heater output on e0heat and map it to sensor 1
M307 H1 B0 S1.00                               ; disable bang-bang mode for heater  and set PWM limit
M143 H1 S300                                   ; set temperature limit for heater 1 to 300C

; Fans
M950 F0 C"fan0" Q500                    	   ; create fan 0 on pin fan0 and set its frequency
M106 P0 C"Part Cooling" S0 H-1                 ; set fan 0 value. Thermostatic control is turned off
M950 F1 C"fan1" Q500                       	   ; create fan 1 on pin fan1 and set its frequency
M106 P1 C"Revo Fan" S255 H1 T40                ; set fan 1 value. Thermostatic control is turned on (fan starts at 40°C)


; Tools
M563 P0 S"revo" H1 F0                          ; define tool 0
G10 P0 X0 Y0 Z0                                ; set tool 0 axis offsets
G10 P0 R0 S0                                   ; set initial tool 0 active and standby temperatures to 0C

; Custom settings are not defined
;M106 P0 T45 H0    							   ; This sets fan 1 to run any time the temperature of heater 1 is above 45 Celsius

; Miscellaneous
M501                                           ; load saved parameters from non-volatile memory
T0                                             ; select first tool

; mks display
M950 P1 C"E.10"
M42 P1 S0
G4 P500
M42 P1 S1
M918 P2 C30 F1000000 E4
