; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+10 on Wed Dec 15 2021 22:06:11 GMT+0100 (Mitteleuropäische Normalzeit)
G90      
	M98 P"homex.g"
	M98 P"homey.g"
	M98 P"homez.g" 
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation
G0 X0 Y0 Z5 F3000
;G1 E5 F600
;G1 E12 F500
G1 Z0.2 F400


